"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.getServerSideProps = void 0;
const head_1 = __importDefault(require("next/head"));
const image_1 = __importDefault(require("next/image"));
const req_1 = require("../src/req");
const Home_module_css_1 = __importDefault(require("../styles/Home.module.css"));
const Home = ({ name }) => {
    return (<div className={Home_module_css_1.default.container}>
      <head_1.default>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </head_1.default>

      <main className={Home_module_css_1.default.main}>
        <h1 className={Home_module_css_1.default.title}>
          Welcome to <a href="https://nextjs.org">尊贵 {name}</a>
        </h1>

        <p className={Home_module_css_1.default.description}>
          Get started by editing{' '}
          <code className={Home_module_css_1.default.code}>pages/index.tsx</code>
        </p>

        <div className={Home_module_css_1.default.grid}>
          <a href="https://nextjs.org/docs" className={Home_module_css_1.default.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={Home_module_css_1.default.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/canary/examples" className={Home_module_css_1.default.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" className={Home_module_css_1.default.card}>
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={Home_module_css_1.default.footer}>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by{' '}
          <span className={Home_module_css_1.default.logo}>
            <image_1.default src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
        </a>
      </footer>
    </div>);
};
exports.default = Home;
async function getServerSideProps(context) {
    const user = await (0, req_1.getApi)('get_user?uid=111');
    return {
        props: { name: user.username }, // will be passed to the page component as props
    };
}
exports.getServerSideProps = getServerSideProps;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguanN4Iiwic291cmNlUm9vdCI6Ii9Vc2Vycy9nYW5jaHVueXUvZGV2L2VnZy1taWR3YXktbmV4dC9zcmMvIiwic291cmNlcyI6WyIuLi9wYWdlcy9pbmRleC50c3giXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7O0FBQ0EscURBQTRCO0FBQzVCLHVEQUE4QjtBQUM5QixvQ0FBbUM7QUFDbkMsZ0ZBQThDO0FBRTlDLE1BQU0sSUFBSSxHQUFhLENBQUMsRUFBRSxJQUFJLEVBQU8sRUFBRSxFQUFFO0lBQ3ZDLE9BQU8sQ0FDTCxDQUFDLEdBQUcsQ0FBQyxTQUFTLENBQUMsQ0FBQyx5QkFBTSxDQUFDLFNBQVMsQ0FBQyxDQUMvQjtNQUFBLENBQUMsY0FBSSxDQUNIO1FBQUEsQ0FBQyxLQUFLLENBQUMsZUFBZSxFQUFFLEtBQUssQ0FDN0I7UUFBQSxDQUFDLElBQUksQ0FBQyxJQUFJLENBQUMsYUFBYSxDQUFDLE9BQU8sQ0FBQyw4QkFBOEIsRUFDL0Q7UUFBQSxDQUFDLElBQUksQ0FBQyxHQUFHLENBQUMsTUFBTSxDQUFDLElBQUksQ0FBQyxjQUFjLEVBQ3RDO01BQUEsRUFBRSxjQUFJLENBRU47O01BQUEsQ0FBQyxJQUFJLENBQUMsU0FBUyxDQUFDLENBQUMseUJBQU0sQ0FBQyxJQUFJLENBQUMsQ0FDM0I7UUFBQSxDQUFDLEVBQUUsQ0FBQyxTQUFTLENBQUMsQ0FBQyx5QkFBTSxDQUFDLEtBQUssQ0FBQyxDQUMxQjtxQkFBVyxDQUFDLENBQUMsQ0FBQyxJQUFJLENBQUMsb0JBQW9CLENBQUMsR0FBRyxDQUFDLElBQUksQ0FBQyxFQUFFLENBQUMsQ0FDdEQ7UUFBQSxFQUFFLEVBQUUsQ0FFSjs7UUFBQSxDQUFDLENBQUMsQ0FBQyxTQUFTLENBQUMsQ0FBQyx5QkFBTSxDQUFDLFdBQVcsQ0FBQyxDQUMvQjtnQ0FBc0IsQ0FBQyxHQUFHLENBQzFCO1VBQUEsQ0FBQyxJQUFJLENBQUMsU0FBUyxDQUFDLENBQUMseUJBQU0sQ0FBQyxJQUFJLENBQUMsQ0FBQyxlQUFlLEVBQUUsSUFBSSxDQUNyRDtRQUFBLEVBQUUsQ0FBQyxDQUVIOztRQUFBLENBQUMsR0FBRyxDQUFDLFNBQVMsQ0FBQyxDQUFDLHlCQUFNLENBQUMsSUFBSSxDQUFDLENBQzFCO1VBQUEsQ0FBQyxDQUFDLENBQUMsSUFBSSxDQUFDLHlCQUF5QixDQUFDLFNBQVMsQ0FBQyxDQUFDLHlCQUFNLENBQUMsSUFBSSxDQUFDLENBQ3ZEO1lBQUEsQ0FBQyxFQUFFLENBQUMsb0JBQW9CLEVBQUUsRUFBRSxDQUM1QjtZQUFBLENBQUMsQ0FBQyxDQUFDLHlEQUF5RCxFQUFFLENBQUMsQ0FDakU7VUFBQSxFQUFFLENBQUMsQ0FFSDs7VUFBQSxDQUFDLENBQUMsQ0FBQyxJQUFJLENBQUMsMEJBQTBCLENBQUMsU0FBUyxDQUFDLENBQUMseUJBQU0sQ0FBQyxJQUFJLENBQUMsQ0FDeEQ7WUFBQSxDQUFDLEVBQUUsQ0FBQyxZQUFZLEVBQUUsRUFBRSxDQUNwQjtZQUFBLENBQUMsQ0FBQyxDQUFDLDBEQUEwRCxFQUFFLENBQUMsQ0FDbEU7VUFBQSxFQUFFLENBQUMsQ0FFSDs7VUFBQSxDQUFDLENBQUMsQ0FDQSxJQUFJLENBQUMsd0RBQXdELENBQzdELFNBQVMsQ0FBQyxDQUFDLHlCQUFNLENBQUMsSUFBSSxDQUFDLENBRXZCO1lBQUEsQ0FBQyxFQUFFLENBQUMsZUFBZSxFQUFFLEVBQUUsQ0FDdkI7WUFBQSxDQUFDLENBQUMsQ0FBQyx5REFBeUQsRUFBRSxDQUFDLENBQ2pFO1VBQUEsRUFBRSxDQUFDLENBRUg7O1VBQUEsQ0FBQyxDQUFDLENBQ0EsSUFBSSxDQUFDLDRHQUE0RyxDQUNqSCxTQUFTLENBQUMsQ0FBQyx5QkFBTSxDQUFDLElBQUksQ0FBQyxDQUV2QjtZQUFBLENBQUMsRUFBRSxDQUFDLGFBQWEsRUFBRSxFQUFFLENBQ3JCO1lBQUEsQ0FBQyxDQUFDLENBQ0E7O1lBQ0YsRUFBRSxDQUFDLENBQ0w7VUFBQSxFQUFFLENBQUMsQ0FDTDtRQUFBLEVBQUUsR0FBRyxDQUNQO01BQUEsRUFBRSxJQUFJLENBRU47O01BQUEsQ0FBQyxNQUFNLENBQUMsU0FBUyxDQUFDLENBQUMseUJBQU0sQ0FBQyxNQUFNLENBQUMsQ0FDL0I7UUFBQSxDQUFDLENBQUMsQ0FDQSxJQUFJLENBQUMsd0dBQXdHLENBQzdHLE1BQU0sQ0FBQyxRQUFRLENBQ2YsR0FBRyxDQUFDLHFCQUFxQixDQUV6QjtvQkFBVSxDQUFDLEdBQUcsQ0FDZDtVQUFBLENBQUMsSUFBSSxDQUFDLFNBQVMsQ0FBQyxDQUFDLHlCQUFNLENBQUMsSUFBSSxDQUFDLENBQzNCO1lBQUEsQ0FBQyxlQUFLLENBQUMsR0FBRyxDQUFDLGFBQWEsQ0FBQyxHQUFHLENBQUMsYUFBYSxDQUFDLEtBQUssQ0FBQyxDQUFDLEVBQUUsQ0FBQyxDQUFDLE1BQU0sQ0FBQyxDQUFDLEVBQUUsQ0FBQyxFQUNuRTtVQUFBLEVBQUUsSUFBSSxDQUNSO1FBQUEsRUFBRSxDQUFDLENBQ0w7TUFBQSxFQUFFLE1BQU0sQ0FDVjtJQUFBLEVBQUUsR0FBRyxDQUFDLENBQ1AsQ0FBQTtBQUNILENBQUMsQ0FBQTtBQUVELGtCQUFlLElBQUksQ0FBQTtBQUVaLEtBQUssVUFBVSxrQkFBa0IsQ0FBQyxPQUF3QjtJQUMvRCxNQUFNLElBQUksR0FBUSxNQUFNLElBQUEsWUFBTSxFQUFDLGtCQUFrQixDQUFDLENBQUM7SUFDbkQsT0FBTztRQUNMLEtBQUssRUFBRSxFQUFFLElBQUksRUFBRSxJQUFJLENBQUMsUUFBUSxFQUFFLEVBQUUsZ0RBQWdEO0tBQ2pGLENBQUE7QUFDSCxDQUFDO0FBTEQsZ0RBS0MifQ==